# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: windows-latest

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: WhiteSource@21
  inputs:
    cwd: '$(System.DefaultWorkingDirectory)'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'techish'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: '3a075cd24d1b362b01e5c291b3aeb80925a595eb'
    cliProjectName: 'WebApplication'
    cliSources: '.'
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: SonarCloudAnalyze@1
  inputs:
    jdkversion: 'JAVA_HOME_11_X64'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'D:/a/1/a/WebApplication.zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'
